name: Despliegue con Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3

      - name: Configurar Node.js (necesario para la CLI de Vercel)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Vercel CLI
        run: npm install --global vercel@latest

      - name: Despliegue Atómico (Lanzamiento Verde)
        id: deploy-to-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          echo "Desplegando la nueva version (Lanzamiento Verde)..."
          VERCEL_DEPLOYMENT_URL=$(vercel --prod --token="$VERCEL_TOKEN" --yes)
          echo "::set-output name=url::$VERCEL_DEPLOYMENT_URL"
          echo "Despliegue exitoso en: $VERCEL_DEPLOYMENT_URL"
      
      - name: Promover a Produccion (Cambio del Trafico)
        run: |
          echo "Promoviendo el despliegue a la URL principal..."
          # El alias es el comando que "cambia el puntero"
          vercel alias set ${{ steps.deploy-to-vercel.outputs.url }} tu-dominio.com --token="${{ secrets.VERCEL_TOKEN }}"
          echo "¡Lanzamiento Azul/Verde completado! El trafico se ha redirigido a la nueva version."
